<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>9657ec71-27ca-4ad4-90ef-be5fcff34b48</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.26" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\InstantProforms.Application\InstantProforms.Application.csproj" />
		<ProjectReference Include="..\InstantProforms.Infrastructure\InstantProforms.Infrastructure.csproj" />
	</ItemGroup>

</Project>