using InstantProforms.Application.Common.Interfaces;
using InstantProforms.Application.Features.Proforms.GetProformById;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace InstantProforms.Infrastructure.Services;

/// <summary>
/// Generates proform PDF documents using QuestPDF.
/// </summary>
public sealed class QuestPdfProformPdfService : IProformPdfService
{
    /// <inheritdoc />
    public byte[] Generate(GetProformByIdResponse proform)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);

                page.Header().Column(column =>
                {
                    column.Item().Text("PROFORM")
                        .FontSize(20)
                        .Bold();

                    column.Item().Text($"Number: {proform.Number}");
                    column.Item().Text($"Status: {proform.Status}");
                    column.Item().Text($"Issued At: {proform.IssuedAtUtc:yyyy-MM-dd HH:mm}");
                });

                page.Content().Column(column =>
                {
                    column.Spacing(10);

                    column.Item().Text($"Client: {proform.ClientName}");
                    column.Item().Text($"Email: {proform.ClientEmail ?? "-"}");
                    column.Item().Text($"Phone: {proform.ClientPhone ?? "-"}");

                    if (!string.IsNullOrWhiteSpace(proform.Notes))
                    {
                        column.Item().Text($"Notes: {proform.Notes}");
                    }

                    column.Item().PaddingTop(10).Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(4);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Description").Bold();
                            header.Cell().Text("Qty").Bold();
                            header.Cell().Text("Unit Price").Bold();
                            header.Cell().Text("Total").Bold();
                        });

                        foreach (var item in proform.Items.OrderBy(x => x.SortOrder))
                        {
                            table.Cell().Text(item.Description);
                            table.Cell().Text(item.Quantity.ToString("0.##"));
                            table.Cell().Text(item.UnitPrice.ToString("N2"));
                            table.Cell().Text(item.Total.ToString("N2"));
                        }
                    });

                    column.Item().PaddingTop(15).AlignRight().Column(totalColumn =>
                    {
                        totalColumn.Item().Text($"Subtotal: {proform.Subtotal:N2}");
                        totalColumn.Item().Text($"Total: {proform.Total:N2}").Bold();
                    });
                });

                page.Footer()
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Span("Generated by InstantProforms");
                    });
            });
        }).GeneratePdf();
    }
}