using InstantProforms.Domain.Common;
using InstantProforms.Domain.Enums;

namespace InstantProforms.Domain.Entities;

/// <summary>
/// Represents a quotation or proforms document generated by a company.
/// </summary>
public sealed class Proform : BaseAuditableEntity
{
    /// <summary>
    /// Gets or sets the company identifier.
    /// </summary>
    public Guid CompanyId { get; set; }

    /// <summary>
    /// Gets or sets the generated proforms number.
    /// </summary>
    public string Number { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the current status of the proforms.
    /// </summary>
    public ProformStatus Status { get; set; } = ProformStatus.Draft;

    /// <summary>
    /// Gets or sets the client name.
    /// </summary>
    public string ClientName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the client email.
    /// </summary>
    public string? ClientEmail { get; set; }

    /// <summary>
    /// Gets or sets the client phone number.
    /// </summary>
    public string? ClientPhone { get; set; }

    /// <summary>
    /// Gets or sets the issue date in UTC.
    /// </summary>
    public DateTime IssuedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets optional notes.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Gets or sets the subtotal amount.
    /// </summary>
    public decimal Subtotal { get; set; }

    /// <summary>
    /// Gets or sets the total amount.
    /// </summary>
    public decimal Total { get; set; }

    /// <summary>
    /// Gets or sets the related company.
    /// </summary>
    public Company Company { get; set; } = null!;

    /// <summary>
    /// Gets or sets the tax percentage applied to the proform.
    /// </summary>
    public decimal TaxPercentage { get; set; }

    /// <summary>
    /// Gets or sets the tax amount applied to the proform.
    /// </summary>
    public decimal TaxAmount { get; set; }
    /// <summary>
    /// Gets or sets the share tokens issued for this proform.
    /// </summary>
    public ICollection<ProformShareToken> ShareTokens { get; set; } = new List<ProformShareToken>();

    /// <summary>
    /// Gets or sets the items in the proforms.
    /// </summary>
    public ICollection<ProformItem> Items { get; set; } = new List<ProformItem>();
}