using InstantProforms.Domain.Common;
using InstantProforms.Domain.Enums;

namespace InstantProforms.Domain.Entities;

/// <summary>
/// Represents a quotation or proforms document generated by a company.
/// </summary>
public sealed class Proform : BaseAuditableEntity
{
    /// <summary>
    /// Gets or sets the company identifier.
    /// </summary>
    public Guid CompanyId { get; set; }

    /// <summary>
    /// Gets or sets the generated proforms number.
    /// </summary>
    public string Number { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the associated saved client identifier.
    /// </summary>
    public Guid? ClientId { get; set; }

    /// <summary>
    /// Gets or sets the current status of the proforms.
    /// </summary>
    public ProformStatus Status { get; set; } = ProformStatus.Draft;

    /// <summary>
    /// Gets or sets the currency used by the proform.
    /// </summary>
    public ProformCurrency Currency { get; set; } = ProformCurrency.Colones;

    /// <summary>
    /// Gets or sets the client name.
    /// </summary>
    public string ClientName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the client email.
    /// </summary>
    public string? ClientEmail { get; set; }

    /// <summary>
    /// Gets or sets the client phone number.
    /// </summary>
    public string? ClientPhone { get; set; }

    /// <summary>
    /// Gets or sets the client identification type snapshot.
    /// </summary>
    public ClientIdentificationType? ClientIdentificationType { get; set; }

    /// <summary>
    /// Gets or sets the client identification number snapshot.
    /// </summary>
    public string? ClientIdentificationNumber { get; set; }

    /// <summary>
    /// Gets or sets the issue date in UTC.
    /// </summary>
    public DateTime IssuedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets the service or delivery location shown in the proform.
    /// </summary>
    public string? Location { get; set; }

    /// <summary>
    /// Gets or sets internal notes kept only inside the application.
    /// </summary>
    public string? InternalNotes { get; set; }

    /// <summary>
    /// Gets or sets the service description section.
    /// </summary>
    public string? ServiceDescription { get; set; }

    /// <summary>
    /// Gets or sets the scope of work section.
    /// </summary>
    public string? ScopeOfWork { get; set; }

    /// <summary>
    /// Gets or sets the service conditions section.
    /// </summary>
    public string? ServiceConditions { get; set; }

    /// <summary>
    /// Gets or sets the payment conditions section.
    /// </summary>
    public string? PaymentConditions { get; set; }

    /// <summary>
    /// Gets or sets the subtotal amount.
    /// </summary>
    public decimal Subtotal { get; set; }

    /// <summary>
    /// Gets or sets the total amount.
    /// </summary>
    public decimal Total { get; set; }

    /// <summary>
    /// Gets or sets the related company.
    /// </summary>
    public Company Company { get; set; } = null!;

    /// <summary>
    /// Gets or sets the related client when the proform is linked to a saved client.
    /// </summary>
    public Client? Client { get; set; }

    /// <summary>
    /// Gets or sets the tax percentage applied to the proform.
    /// </summary>
    public decimal TaxPercentage { get; set; }

    /// <summary>
    /// Gets or sets the tax amount applied to the proform.
    /// </summary>
    public decimal TaxAmount { get; set; }
    /// <summary>
    /// Gets or sets the share tokens issued for this proform.
    /// </summary>
    public ICollection<ProformShareToken> ShareTokens { get; set; } = new List<ProformShareToken>();

    /// <summary>
    /// Gets or sets the items in the proforms.
    /// </summary>
    public ICollection<ProformItem> Items { get; set; } = new List<ProformItem>();
}
